# Site settings
# in the templates available like {{ site.myvariable }}.
title: My Web
email: 1045691954@qq.com
brand: YuanyiLi
headline: Show My Protfolio
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: Yuanyi Li. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 1045691954@qq.com
phone: +61 0401775034

# Tracking
googleAnalitycsID: UA-83933844-1


theme: jekyll-theme-cayman